// Generated by NativeGen v0.1.0
#pragma once

#include <gtk/gtk.h>
#include <string>

class NGLinuxWindow
{
private:
  GtkApplication *app;
  static void onActivate(GtkApplication *app);
public:
  NGLinuxWindow();
  void run();
};
