# Generated by NativeGen v0.1.0

CC := g++
ARGS := -std=c++17 -g -Wall -m64
INCLDIR := $(shell pkg-config --cflags gtk+-3.0)
LIBS := $(shell pkg-config --libs gtk+-3.0)
OUTDIR := build/SimpleWindow

all: build clean run

build:
	$(CC) -c ./src/*.cpp ./src/components/*.cpp ./src/components/linux/*.cpp $(INCLDIR)
	$(CC) *.o -o $(OUTDIR) $(LIBS)

clean:
	rm *.o

run:
	./$(OUTDIR)

.PHONY: all build clean run
