// Generated by NativeGen v0.1.0
// All of your logic goes in this file.

#include "include/App.hpp"

// Creates a new application and builds its UI
App::App()
{
  // Build GUI (done by NativeGen)
  window = new NGWindow();

  // Event callbacks go here...
}

// Runs the application's main loop
void App::run()
{
  window->run();
}
