// Generated by NativeGen v0.1.0

#pragma once
#include "../linux/include/NGLinuxWindow.hpp"

class NGWindow
{
private:
#ifdef __linux__
  NGLinuxWindow *window;
#endif
public:
  NGWindow();
  void run();
};
